/*

 BLACK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Paul\Documents\Programm\gameboy\hello_world\files\stars.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define blackscreen_mapWidth 20
#define blackscreen_mapHeight 18
#define blackscreen_mapBank 0

extern unsigned char blackscreen_map[];

/* End of BLACK.H */
