/*

 SPLASH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Paul\Documents\Programm\gameboy\hello_world\files\stars.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define imute_dataWidth 20
#define imute_dataHeight 18
#define imute_dataBank 0

extern unsigned char imute_data[];

/* End of SPLASH.H */
