/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 18
   Tile set      : stars.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define galaxy_backgroundWidth 80
#define galaxy_backgroundHeight 18
#define galaxy_backgroundBank 0

extern unsigned char galaxy_background[];

/* End of BACKGROUND.H */
